### ISSUE TITLE
The pop-up doesn't look good when the extension(Trigger-Fixer) is placed in the Overflow Menu

### ISSUE THREAD

**Issue by MrFox14** [Mistyttm/trigger-fixer#1]
Steps To Reproduce:
1. Click the Hamburger Menu
2. Click More Tools
3. Click Customize Toolbar
4. Drag Trigger-Fixer's icon to the Overflow Menu
5. Open a new tab
6. Click the More Tools/Overflow Menu Icon in the toolbar
7. Click Trigger-Fixer
Expected Result:
The “Edit Trigger List” button should be in the middle.
Actual Result: 
The “Edit Trigger List” button is on the left-upper side.

**Comment by Mistyttm** [comment]
Without doing a full redesign of how the pop-up menu works, spacing has been added to fix this issue.

Thanks :D
